# Generated by Django 2.1.2 on 2019-05-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Cat',
            new_name='cat_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Cat_Name',
        ),
    ]
